---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
     - role: rhelbuild
       role1_action: "run action for role1"
       role2_action: "run action for role2"
       role3_action: "run action for role3"

